### ISSUE TITLE
Can't download pytorch_course.yml

### ISSUE THREAD

**Issue by pszgaspar** [sib-swiss/pytorch-practical-training#1]
Hi,

Apparently Google considers downgit.git.io to be a harmful site. After ignoring security risk message I still get:
Error! Server failure or wrong url

I tried on Chrome, Safari and Firefox. All the same, can't get the file. Any other way to share the .yml?

Best,
Gaspar

**Comment by AntoniGrantos** [comment]
I had the same issue, but if you look at the list all the provided files, you'll see one called pytorch_course.yml. This one doesn't get blocked and you can download it. However, it appears to be an empty file and when I tried to create a conda env, it didn't work.

Best,
Antoni

**Comment by pszgaspar** [comment]
I ended up going with method 2 for the setup. That seemed to have worked.

**Comment by bri2020** [comment]
What is method 2? If I download everything (using `git clone https://github.com/sib-swiss/pytorch-practical-training.git`) and want to use the pytorch_course.yml it is empty too.

**Comment by pszgaspar** [comment]
I have the conda env set up with all the dependencies (method 2: conda and pip commands to install - on the github link in the email), no other course material though.

**Comment by WandrilleD** [comment]
yml file and link have been fixed
